# Generated by Django 4.2.23 on 2025-08-19 20:36

import app.models.file_submission
import app.models.image_submission
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="User's first name.", max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="User's last name.", max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(help_text="User's email address. Must be unique.", max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('ADMIN', 'Admin'), ('REGISTERED', 'Registered User')], default='REGISTERED', help_text="Defines the user's role and access level in the system.", max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TextSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Name for the submission', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the submission was created.')),
                ('content', models.TextField(help_text='The text content submitted for AI detection analysis.', max_length=5000)),
                ('character_count', models.PositiveIntegerField(blank=True, help_text='Number of characters in the submission.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'text_submissions',
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'created_at'], name='text_submis_user_id_da9e3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TextAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the feedback.', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current status of the analysis.', max_length=20)),
                ('object_id', models.UUIDField()),
                ('detection_result', models.CharField(blank=True, choices=[('AI_GENERATED', 'AI Generated'), ('HUMAN_WRITTEN', 'Human Written'), ('UNCERTAIN', 'Uncertain')], help_text='Final decision on whether content was generated by AI.', max_length=20, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score between 0.0 and 1.0 (higher = more confident).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('probability', models.FloatField(blank=True, help_text='Probability that content is AI-generated (0.0 to 1.0).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reason', models.TextField(blank=True, help_text='Explanation of why the content was classified as AI-generated or human-written.', null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Time taken to process the analysis in milliseconds.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when analysis started.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when analysis was completed.', null=True)),
                ('flagged_content', models.JSONField(blank=True, default=list, help_text='List of content flagged as potentially AI-generated.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'text_analysis_results',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='text_analys_content_d37c8e_idx'), models.Index(fields=['status'], name='text_analys_status_de9a70_idx'), models.Index(fields=['detection_result'], name='text_analys_detecti_69ba34_idx'), models.Index(fields=['created_at'], name='text_analys_created_a2ef05_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImageSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Name for the submission', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the submission was created.')),
                ('image', models.ImageField(help_text='Image file for AI detection analysis. Supported formats: JPG, JPEG, PNG.', upload_to=app.models.image_submission.image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image width in pixels.', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image height in pixels.', null=True)),
                ('user', models.ForeignKey(help_text='User who made this submission.', on_delete=django.db.models.deletion.CASCADE, related_name='image_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image_submissions',
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'created_at'], name='image_submi_user_id_705d75_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the feedback.', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current status of the analysis.', max_length=20)),
                ('object_id', models.UUIDField()),
                ('detection_result', models.CharField(blank=True, choices=[('AI_GENERATED', 'AI Generated'), ('HUMAN_WRITTEN', 'Human Written'), ('UNCERTAIN', 'Uncertain')], help_text='Final decision on whether content was generated by AI.', max_length=20, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score between 0.0 and 1.0 (higher = more confident).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('probability', models.FloatField(blank=True, help_text='Probability that content is AI-generated (0.0 to 1.0).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reason', models.TextField(blank=True, help_text='Explanation of why the content was classified as AI-generated or human-written.', null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Time taken to process the analysis in milliseconds.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when analysis started.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when analysis was completed.', null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'image_analysis_results',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='image_analy_content_2ef2ee_idx'), models.Index(fields=['status'], name='image_analy_status_8f880a_idx'), models.Index(fields=['detection_result'], name='image_analy_detecti_927788_idx'), models.Index(fields=['created_at'], name='image_analy_created_f3b18b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Name for the submission', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the submission was created.')),
                ('file', models.FileField(help_text='Document file for AI detection analysis. Supported formats: PDF, TXT, DOCX.', upload_to=app.models.file_submission.file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'docx'])])),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('file_type', models.CharField(blank=True, help_text='File extension (pdf, txt, docx).', max_length=10, null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Text content extracted from the file.', null=True)),
                ('character_count', models.PositiveIntegerField(blank=True, help_text='Number of characters in the submission.', null=True)),
                ('user', models.ForeignKey(help_text='User who made this submission.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_submissions',
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'created_at'], name='file_submis_user_id_83cba7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the feedback.', primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('THUMBS_UP', 'Thumbs Up'), ('THUMBS_DOWN', 'Thumbs Down')], help_text="User's rating for the AI analysis result.", max_length=15)),
                ('comment', models.TextField(blank=True, help_text='Optional comment about the analysis result.', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the submission was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the submission was last updated.')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who provided the feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
                'indexes': [models.Index(fields=['user', 'created_at'], name='feedback_user_id_8e9eb5_idx'), models.Index(fields=['rating'], name='feedback_rating_ed839f_idx'), models.Index(fields=['content_type', 'object_id'], name='feedback_content_25f1b0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_feedback_per_user_submission'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'user_type'], name='users_email_e7d39f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name'], name='users_first_n_de8b69_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_ty_578f8f_idx'),
        ),
    ]
