# Generated by Django 4.2.23 on 2025-09-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textanalysisresult',
            name='flagged_content',
        ),
        migrations.AddField(
            model_name='textanalysisresult',
            name='analysis_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed analysis including found patterns, keywords, etc.'),
        ),
        migrations.AddField(
            model_name='textanalysisresult',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='Model confidence in the prediction (0.0 - 1.0)'),
        ),
        migrations.AddField(
            model_name='textanalysisresult',
            name='detection_reasons',
            field=models.JSONField(blank=True, default=list, help_text='List of detection reasons from Claude analysis'),
        ),
        migrations.AddField(
            model_name='textanalysisresult',
            name='enhanced_analysis_used',
            field=models.BooleanField(default=False, help_text='Whether Claude enhanced analysis was used'),
        ),
        migrations.AddField(
            model_name='textanalysisresult',
            name='statistics',
            field=models.JSONField(blank=True, default=dict, help_text='Text statistics (word count, sentences, AI patterns, etc.)'),
        ),
        migrations.AddIndex(
            model_name='textanalysisresult',
            index=models.Index(fields=['probability'], name='text_analys_probabi_fcbf64_idx'),
        ),
        migrations.AddIndex(
            model_name='textanalysisresult',
            index=models.Index(fields=['enhanced_analysis_used'], name='text_analys_enhance_9251de_idx'),
        ),
    ]
