# Generated by Django 5.2.6 on 2025-09-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_feedback_admin_notes_feedback_resolved_at_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='admin_notes',
        ),
        migrations.AddField(
            model_name='imageanalysisresult',
            name='analysis_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed analysis including detection reasons and Claude explanation'),
        ),
        migrations.AddField(
            model_name='imageanalysisresult',
            name='enhanced_analysis_used',
            field=models.BooleanField(default=False, help_text='Whether enhanced visual analysis (Claude) was used'),
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='image_format',
            field=models.CharField(blank=True, help_text='Image format (jpg, png, etc.)', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='imageanalysisresult',
            index=models.Index(fields=['enhanced_analysis_used'], name='image_analy_enhance_f04d69_idx'),
        ),
        migrations.AddIndex(
            model_name='imagesubmission',
            index=models.Index(fields=['image_format'], name='image_submi_image_f_794fe6_idx'),
        ),
    ]
