# Generated by Django 5.2.6 on 2025-09-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_feedback_admin_notes_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedback',
            name='unique_feedback_per_user_submission',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='resolved_by',
        ),
        migrations.AlterField(
            model_name='imageanalysisresult',
            name='analysis_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed analysis including detection reasons from visual analysis'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status'], name='feedback_status_d7fa3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_feedback_per_user_analysis'),
        ),
    ]
